spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quizDB
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
management:
  security:
    enabled: false
  port: 9000
  context-path: /admin
    

